const menuToggle=document.getElementById("menuToggle");
const navMenu=document.getElementById("navMenu");
menuToggle.addEventListener("click",()=>{navMenu.classList.toggle("open");const i=menuToggle.querySelector("i");i.classList.toggle("fa-bars");i.classList.toggle("fa-xmark")});
document.querySelectorAll(".nav-link").forEach(l=>l.addEventListener("click",()=>{navMenu.classList.remove("open");const i=menuToggle.querySelector("i");i.classList.add("fa-bars");i.classList.remove("fa-xmark")}));

const themeToggle=document.getElementById("themeToggle");
const savedTheme=localStorage.getItem("portfolio-theme");
if(savedTheme==="dark"){document.body.classList.add("dark");themeToggle.innerHTML='<i class="fas fa-sun"></i>'}
themeToggle.addEventListener("click",()=>{document.body.classList.toggle("dark");const dark=document.body.classList.contains("dark");localStorage.setItem("portfolio-theme",dark?"dark":"light");themeToggle.innerHTML=dark?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>'});

const sections=document.querySelectorAll("section");
const navLinks=document.querySelectorAll(".nav-link");
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(l=>l.classList.toggle("active",l.getAttribute("href")===`#${e.target.id}`))}}),{threshold:.3});
sections.forEach(s=>sectionObserver.observe(s));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");revealObserver.unobserve(e.target)}}),{threshold:.08});
document.querySelectorAll(".reveal").forEach(e=>revealObserver.observe(e));

const projects={
 cholokerp:{title:"CholokERP",description:"An enterprise ERP and HRIS platform designed around modular architecture, multi-tenancy and provider-independent persistence.",architecture:"Modular Monolith with clear business capability boundaries and shared platform services.",problem:"Enterprise HR and ERP workflows require many interconnected capabilities without turning the system into a tightly coupled codebase.",solution:"Separate business modules, platform services and persistence concerns while keeping deployment simple and allowing future independent scaling.",decisions:["Modular boundaries","Multi-tenancy","Workflow & approvals","Notification & audit","Provider-flexible persistence","Idempotent transactions"],tech:".NET, ASP.NET Core, EF Core, SQL Server, PostgreSQL, MySQL, Clean Architecture, CQRS"},
 diagnosphere:{title:"DiagnoSphere",description:"A SaaS diagnostic center platform for patient management, billing, tests, doctors, commissions, expenses and inventory.",architecture:"Multi-tenant SaaS architecture with domain-focused modules and centralized platform capabilities.",problem:"Diagnostic centers need a single operational platform connecting registration, services, billing, doctor commissions and inventory.",solution:"Model healthcare workflows as modular capabilities with tenant-aware configuration, pricing, billing and reporting.",decisions:["Patient-centric workflows","Billing engine","Doctor commission rules","Expense management","Inventory/POS integration","Tenant isolation"],tech:".NET, ASP.NET Core, EF Core, SQL Server, JavaScript, Bootstrap, Kendo UI"},
 radiology:{title:"Radiology Platform",description:"A cloud-ready radiology platform designed around DICOM study management and distributed radiologist worklists.",architecture:"Service-oriented SaaS design with study processing, assignment, commission and settlement capabilities.",problem:"Radiology operations require efficient study routing, radiologist assignment, worklist management and transparent financial settlement.",solution:"Centralize study intake and assignment while keeping radiologist, commission and settlement capabilities independently manageable.",decisions:["DICOM study flow","Rule-based assignment","Supervisor override","Radiologist worklist","Commission calculation","Settlement"],tech:".NET, ASP.NET Core, DICOM ecosystem, REST APIs and relational databases"}
,
 eprc:{title:"EPRC Research Application Submission & Funding",description:"A government project for web-based research application submission and funding management.",architecture:"Workflow-driven web application for structured application intake, review and funding processing.",problem:"Research funding programs require a controlled digital process for receiving, evaluating and processing applications.",solution:"Digitize the application lifecycle and create a transparent workflow for submission, review and funding decisions.",decisions:["Online submission","Application workflow","Research funding","Review process"],tech:"Web application, relational database, workflow-oriented business processing"},
 etender:{title:"E-Tender",description:"Web-based tender submission and processing platform for a private organization.",architecture:"Business workflow platform focused on controlled tender submission and processing.",problem:"Manual tender processes can create delays, inconsistent tracking and limited visibility.",solution:"Provide a centralized web workflow for tender submission, processing and operational tracking.",decisions:["Tender submission","Workflow processing","Status tracking","Digital records"],tech:"Web application, relational database and business workflow"},
 career:{title:"Career Portal",description:"Recruitment portal integrated with HRIS to connect candidate intake with enterprise recruitment processes.",architecture:"Candidate-facing recruitment portal integrated with enterprise HRIS workflows.",problem:"Recruitment teams need structured candidate collection and smooth transfer of relevant information into HR processes.",solution:"Connect online career applications with HRIS-driven recruitment workflows for a more consistent hiring process.",decisions:["Online applications","Candidate workflow","HRIS integration","Recruitment processing"],tech:"Web application, HRIS integration, relational database and REST-based integration"}};
const modal=document.getElementById("projectModal"),modalContent=document.getElementById("modalContent");
document.querySelectorAll(".project-link").forEach(b=>b.addEventListener("click",()=>{const p=projects[b.dataset.project];modalContent.innerHTML=`<h3 class="modal-title">${p.title}</h3><p class="modal-description">${p.description}</p><div class="modal-section"><h4>Problem</h4><p>${p.problem}</p></div><div class="modal-section"><h4>Architecture</h4><p>${p.architecture}</p></div><div class="modal-section"><h4>Engineering Decisions</h4><div class="modal-flow">${p.decisions.map(x=>`<span class="modal-chip">${x}</span>`).join("")}</div></div><div class="modal-section"><h4>Solution</h4><p>${p.solution}</p></div><div class="modal-section"><h4>Technology</h4><p>${p.tech}</p></div>`;modal.classList.add("show");document.body.style.overflow="hidden"}));
function closeModal(){modal.classList.remove("show");document.body.style.overflow=""}
document.getElementById("modalClose").addEventListener("click",closeModal);
modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});

const archData={
 platform:{title:"Modular Enterprise Platform",description:"A modular application keeps business capabilities isolated while shared platform services provide cross-cutting infrastructure.",nodes:[["Client Applications"],["ASP.NET Core API"],["Auth","Core","HRM","Platform"],["Workflow","Notification","Audit","Scheduler"],["Persistence"],["SQL Server","PostgreSQL","MySQL"]]},
 security:{title:"Security Architecture",description:"Security is layered: identity authenticates the actor, authorization determines capability, business grants constrain scope, and audit records important actions.",nodes:[["Client"],["Authentication"],["Role / Permission"],["User / Access Grants"],["Business Authorization"],["Audit"]]},
 data:{title:"Provider-Flexible Data Architecture",description:"The application can select a supported database provider through configuration while domain and application layers remain independent of provider-specific details.",nodes:[["Application"],["Persistence Abstraction"],["SQL Server","PostgreSQL","MySQL"],["Provider-specific Migrations"]]},
 processing:{title:"Background & Event Processing",description:"Long-running and asynchronous work is moved away from request threads using workers, an outbox pattern and platform services.",nodes:[["API Request"],["Transaction + Outbox"],["Worker / Scheduler"],["Processing Engine"],["Notification / Integration"],["Audit"]]}
};
const archVisual=document.getElementById("archVisual"),archDescription=document.getElementById("archDescription");
function renderArch(key){const d=archData[key];archVisual.innerHTML=d.nodes.map((row,i)=>`${i?'<div class="flow-arrow"></div>':""}<div class="${row.length>1?'flow-row':''}">${row.map((x,j)=>`<div class="flow-node ${i===1?'primary':i===row.length-1&&row.length===1?'accent':''}">${x}</div>`).join("")}</div>`).join("");archDescription.innerHTML=`<h3>${d.title}</h3><p>${d.description}</p>`}
renderArch("platform");
document.querySelectorAll(".arch-tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".arch-tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");renderArch(t.dataset.arch)}));

document.getElementById("currentYear").textContent=new Date().getFullYear();
